<?php
return array(
    '1' => array(
        'effect_max' => 150.0,
        'effect_min' => 100.0,
        'equip_effect_type' => 1,
        'equip_id' => 1,
        'equip_level' => 4,
        'equip_name' => '雷神之剑',
        'equip_type' => 1,
    ),
    '2' => array(
        'effect_max' => 20.0,
        'effect_min' => 20.0,
        'equip_effect_type' => 2,
        'equip_id' => 2,
        'equip_level' => 4,
        'equip_name' => '龙王之铠',
        'equip_type' => 2,
    ),
    '3' => array(
        'effect_max' => 20.0,
        'effect_min' => 20.0,
        'equip_effect_type' => 2,
        'equip_id' => 3,
        'equip_level' => 4,
        'equip_name' => '龙王护腿',
        'equip_type' => 3,
    ),
    '4' => array(
        'effect_max' => 20.0,
        'effect_min' => 20.0,
        'equip_effect_type' => 2,
        'equip_id' => 4,
        'equip_level' => 4,
        'equip_name' => '龙王之盔',
        'equip_type' => 4,
    ),
    '5' => array(
        'effect_max' => 20.0,
        'effect_min' => 20.0,
        'equip_effect_type' => 4,
        'equip_id' => 5,
        'equip_level' => 4,
        'equip_name' => '龙王之靴',
        'equip_type' => 5,
    ),
    '6' => array(
        'effect_max' => 20.0,
        'effect_min' => 20.0,
        'equip_effect_type' => 2,
        'equip_id' => 6,
        'equip_level' => 4,
        'equip_name' => '龙王之盾',
        'equip_type' => 6,
    ),
    '7' => array(
        'effect_max' => 20.0,
        'effect_min' => 20.0,
        'equip_effect_type' => 5,
        'equip_id' => 7,
        'equip_level' => 4,
        'equip_name' => '龙王护手',
        'equip_type' => 7,
    ),
    '8' => array(
        'effect_max' => 40.0,
        'effect_min' => 40.0,
        'equip_effect_type' => 5,
        'equip_id' => 8,
        'equip_level' => 4,
        'equip_name' => '冰之指环',
        'equip_type' => 8,
    ),
    '9' => array(
        'effect_max' => 30.0,
        'effect_min' => 30.0,
        'equip_effect_type' => 3,
        'equip_id' => 9,
        'equip_level' => 4,
        'equip_name' => '冰之项链',
        'equip_type' => 9,
    ),
);
